CirclonGroup/angular-tree-component

- .gitignore
- .npmignore
- angular2-tree-component.ts
- lib/angular2-tree.ts
- lib/components/tree-node-content.component.ts
- lib/components/tree-node.component.ts
- lib/components/tree.component.ts
- lib/constants/events.ts
- lib/models/tree-node.model.ts
- lib/models/tree-options.model.ts
- lib/models/tree.model.ts
- package.json
- tsconfig.json
- typings.json
I made three changes:
1. Updated the setData function to account for a non-default childrenField
2. Changed the way TreeNodeContent is being loaded.
- I'm using ComponentResolver instead of DynamicComponentLoader, since evidently DynamicComponentLoader is being deprecated.  (http://stackoverflow.com/a/35508835/5191105)
- I removed the setTimeout before loading TreeNodeContent and instead use componentRef.changeDetectorRef.detectChanges() once it is instantiated.
3. Changed `#node of ...` to `let node of ...` since they like to change the syntax every couple weeks.
> Fix non-default childrenField, TreeNodeContent not rendering, added dblclick and contextmenu events

- lib/components/tree-node.component.ts
- lib/components/tree.component.ts
Setting ViewEncapsulation to None so the styles can be overwritten as proposed in the README
> Set ViewEncapsulation to None to allow override of styles

- lib/models/tree-node.model.ts
There is an issue with the **isExpanded** field of the initial model. Currently the tree component just ignores it. I found the problem - a typo in a config field name. Now it should work fine.
> Fix isExpanded typo

- package.json
npm installing angular2-tree-component resulted in an error due to failing postinstall script. 
This PR fixes it.
> Changed postinstall script to prebuild in package.json ("typings install")

- package.json
Having `typings` as a regular dependency, rather than a dev dependency, means that other projects keep failing when using post 1.x version of typings.
This change moves typings from `dependencies` to `devDependecies`.
> Move typings into dev dependencies

- package.json
- tsconfig.json
As a library, the `dependencies/peerDependencies` should be limited to exactly what is needed at runtime when using this library. Any other dependencies required for developing, building or running included examples should be added as `devDependencies`.
This PR cleans up the dependencies of the library, while also updating the Angular 2 peerDependencies to match version 2.3.0.
> Update to Angular 2.3.0 and update dependencies

- package.json
- tsconfig.json
By removing the `@types/core-js` dependency, and updating `tsconfig` to use the `lib` option, there is no longer a compile-time (or run-time) dependency on `core-js`, even though it will be used for any polyfills at run-time.
Additionally, since `core-js` contains all the necessary polyfills for Reflect Metadata, the `reflect-metadata` dependency can also be removed, please see angular/angular.io#1748.
Fixes #139
> Use tsconfig instead of @types/core-js

- lib/directives/tree-drag.directive.ts
fix #117 
http://stackoverflow.com/questions/19055264/why-doesnt-html5-drag-and-drop-work-in-firefox
> fix the drag and drop Firefox issue

- lib/models/tree-options.model.ts
This PR prevents:
```
Error in ./TreeNodeComponent class TreeNodeComponent - inline template:16:12 caused by: Cannot read property 'mouse' of undefined
```
and fixes #198.
> fix(tree-options): fix cannot read property of undefined

- lib/directives/tree-drag.directive.ts
This fixes the following error in IE9 & 10: 'unexpected call to method or property access'. In short, IE doesn't support MIME types and only recognizes 'text' and 'URL' as valid data types. HTML5 supports both for backwards compatibility so this change would not break modern browsers. More deatiled explanation here: http://www.developerfusion.com/article/144828/the-html5-drag-and-drop-api/.
> Drag and drop fix for IE9+

- lib/models/tree-node.model.ts
The targets of current `doForAll` are only children, not all descendants.
I fixed it.
> Run doForAll recursively

- lib/angular-tree-component.ts
- lib/components/tree-node-collection.component.ts
- package.json
When bump version, the version of angular-tree-component in example/cli/package.json also should be updated.
Closes #238
> upgrade dependency of mobx-angular

- lib/models/tree-options.model.ts
Hi,
Thanks for your work on this neat plugin. 
Set mouse 'click' option to TREE_ACTIONS.TOGGLE_EXPANDED, then click on first node in the tree, then hit "space" bar on your keyboard. An error is raised. Proposed fix may not be the correct way to fix that, I guess node should be checked before being sent to  this line where toggleActivated is called on it.
Best regards,
Greg
> Fix TypeError: Cannot read property 'toggleActivated' of null

- lib/directives/tree-drop.directive.ts
TreeDraggedElement is set on dragstart in tree-drag.directive. That directive also unset the element on dragend. However, this is only done if the position for the dragend is on the same element as the dragstart. The element should be removed also when the dragging is stopped somewhere else. This fix sets the element to null in the onDrop method in tree-drop.directive.
Issue: https://github.com/500tech/angular-tree-component/issues/318
> Set treeDraggedElement to null on drop

- lib/models/tree-node.model.ts
I verified that @mikedobrin's recommended fix for issue #220 works in my use case and the result passes project tests invoked with the npm `test` script.
> Prevent overwriting existing node ids to allow use with immutable objects

- rollup.config.js
There are a variety of issues submitted due to the UMD file created by rollup being incorrect: #331, #405,  #363, #308, #303, #298, etc... (just about any issue with the 'SystemJS' label) because the CommonJS plugin for rollup did not recognize lodash's exported functions. While that can be fixed with the `namedExports` property, instead I just removed it (along with mobx and mobx-angular) from the UMD bundle since they are as dependencies in package.json. I also suppressed the (spurious?) warnings rollup issued about "'this' keyword is equivalent to undefined," as I figure they probably drowned out the warnings about the unrecognized lodash exports.
FWIW, it may be a good idea to use [rollup-plugin-auto-external](https://www.npmjs.com/package/rollup-plugin-auto-external) to automatically …
> Removing some libraries from umd bundle and suppressing some rollup warnings

- lib/defs/api.ts
- lib/models/tree-node.model.ts
- lib/models/tree-options.model.ts
Allow the user to change which field is checked to determine whether a node has children.
For example, if your nodes have a `isDirectory` attribute that indicates whether there are children, use:
```typescript
options = { hasChildrenField: 'isDirectory' }
```
> Add hasChildrenField option to TreeOptions

- lib/components/tree.component.ts
`this.treeModel.setData` run every time a component input changed. It is unnecessary for example in case of the `state` input (changes of `state` caused performance issues with bigger trees).
> Optimize onChanges in tree component

- lib/defs/api.ts
> Improved type definition of IDTypeDictionary to avoid "no implicit any" error

- package-lock.json
- package.json
- rollup.config.js
The `mobx` and `mobx-angular` libraries were being bundled into the UMD file.
Apart from making the bundle unnecessarily large, it also breaks Angular v9's ngcc processing.
> Do not bundle external 3rd party libraries

- projects/angular-tree-component/src/lib/components/tree.component.ts
Bugfix: Typing correction addressing Issue #795.
> Correct `TreeComponent.options` typing to allow `angularCompilerOptions.strictTemplates: true`

- projects/angular-tree-component/src/lib/angular-tree-component.module.ts
- projects/angular-tree-component/src/lib/models/tree-dragged-element.model.ts
- projects/example-app/src/app/app.module.ts
Since Angular 6, the `@Injectable` decorator has allowed for an optional `providedIn` object parameter  to specify the module in which services should be provided as the as [the preferred alternative](https://angular.io/guide/singleton-services#using-providedin) to the `Providers` array in the `@NgModule()` decorator. This PR provides the `TreeDraggedElement` provider using the new `providedIn` syntax to improve bundle sizes by enabling tree-shaking and allowing Angular Tree Component to bundled in lazy-loaded modules without losing the ability to drag & drop across TreeComponents in different modules that running `TreeDraggedElement` as a Service Singleton allows.
The removal of the `TreeModule.forRoot()` method in this PR introduces a breaking change.
> Use `@Injectable({providedIn: 'root'})` instead of `TreeModule.forRoot()` to provide `TreeDraggedElement`

- package-lock.json
- package.json
- projects/angular-tree-component/ng-package.json
- projects/angular-tree-component/package.json
Only a few projects will use mobx, so we will bundle it with the tree component.
> fix: include mobx as dependency

- package-lock.json
- package.json
- projects/angular-tree-component/package.json
- projects/angular-tree-component/src/lib/components/tree-node-wrapper.component.ts
- projects/angular-tree-component/src/lib/components/tree-node.component.ts
- projects/angular-tree-component/src/lib/components/tree-viewport.component.ts
- projects/angular-tree-component/src/lib/components/tree.component.ts
- projects/angular-tree-component/src/lib/defs/api.ts
- projects/angular-tree-component/src/lib/models/tree-node.model.ts
- projects/angular-tree-component/src/lib/models/tree-options.model.ts
- projects/angular-tree-component/src/lib/models/tree.model.ts
```
[ ] Bugfix
[x] Feature
```
`lodash-es` ist dependency. The `getNodeById` method takes a method for filtering nodes that has to fit the lodash version of find.
Closes #
`lodash-es` is not a dependency anymore. The `getNodeById` method takes a method for filtering nodes that has to fit the javascript version of find.
```
[x] Yes
[ ] No
```
Check if your `getNodeById` method is using a method not compatible with the javascript version of find.
> feat: remove lodash-es

- projects/angular-tree-component/src/lib/models/tree-node.model.ts
- projects/angular-tree-component/src/lib/models/tree.model.ts
closes #893
```
[x] Bugfix
[ ] Feature
```
Closes #893
`getFirstChild` and `getLastChild` return `TreeNode` or `null` again.
```
[ ] Yes
[x] No
```
> fix: return TreeNode for first and last child

- projects/angular-tree-component/src/lib/components/tree-viewport.component.ts
- [  x ] The commit message follows our guidelines: https://github.com/CirclonGroup/angular-tree-component/blob/master/CONTRIBUTING.md#commit-message-guidelines
```
[ x ] Bugfix
[ ] Feature
```
Closes #852 
Loading is not stuck anymore when using `virtualScroll: true`
```
[ ] Yes
[ x ] No
```
> fix: reverting change to add scroll eventhandler inside ng cd (#852)
