CirclonGroup/angular-tree-component

package.json

update to Angular RC2, remove router/upgrade peerDeps

---

package.json

updating to RC3

---

lib/components/tree-node.component.ts

This is what I had in mind for the [Node expand button can get out of line](https://github.com/500tech/angular2-tree-component/issues/80) issue. Obviously not as good as what you had in mind - I was wondering if you would consider something like that as an interim solution?

Added wrapper to keep node in line with toggle

---

lib/components/tree-node-collection.component.ts

Fixing bug for 'Console warning on empty nodes #195'

---

lib/models/tree-node.model.ts

Allow for ID=0

---

example/cli/src/app/fulltree/fulltree.component.ts
lib/components/tree-node-drop-slot.component.ts
lib/defs/api.ts
lib/directives/tree-drop.directive.ts
lib/models/tree-node.model.ts
lib/models/tree-options.model.ts

Passing event-object to allowDrop-function

---

lib/vendor/closest.ts

I had to add this by working with the angular universal.
Since there was an error
$ node dist/server.js 
```
/Users/kkaabbaa/projects/johndeverall/scn-app/dist/server.js:22830
if (typeof Element.prototype.matches !== 'function') {
^
```
This is because node.js does not have an object of type Element. From HTML DOM
With this fix everything works fine

Fixed for angular universal - if (typeof Element.prototype.matches !== 'function') {

---

lib/defs/api.ts
lib/models/tree-options.model.ts
lib/models/tree.model.ts

It is very useful to have possibility to assing id also for root node and I can't see a way to do it right now.

assing custom id to virtualRoot node

---

lib/components/tree-node-wrapper.component.ts

A fix for https://github.com/500tech/angular-tree-component/issues/465

Tree node wrapper should output the templates

---

lib/models/tree.model.ts

Fixed argument order for Array.reduce

---

lib/defs/api.ts

https://angular2-tree.readme.io/docs/save-restore

added the missing property selectedLeafNodeIds

---

example/cli/src/app/async/async.component.ts
lib/models/tree-node.model.ts

* fix checkbox / loading of async children take over selection of parent #531 #519

Checkbox keep parent selection on async children (#531) (#519)

---

lib/models/tree.model.ts

Allows you to swap out nodes, update, and then calculateExpandedNodes afterwards. 
#520

public method calculateExpandedNodes #520

---

lib/models/tree.model.ts

extended selection-api for nodes
- by selectedLeafNodes
- by hiddenNodes

extended selection-api for nodes

---

package.json
projects/angular-tree-component/package.json

Add licence to package.json of library.
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Closes #842 
```
[ ] Yes
[x] No
```

build: add license to library package.json

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-request.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Outdated issue template.
Closes #850
New issue templates with clearer guidance, stackblitz links, different style for different issues.
```
[ ] Yes
[x] No
```

docs: updated issue templates

---

projects/angular-tree-component/src/lib/models/tree-virtual-scroll.model.ts

- [ X ] The commit message follows our guidelines: https://github.com/CirclonGroup/angular-tree-component/blob/master/CONTRIBUTING.md#commit-message-guidelines
```
[ X ] Bugfix
[ ] Feature
```
Closes #463 
```
[ ] Yes
[ X ] No
```

fix: do not load whole child collection with virtual scroll (#463)

---

projects/angular-tree-component/src/lib/models/tree-node.model.ts
projects/angular-tree-component/src/lib/models/tree.model.ts
projects/angular-tree-component/tslint.json
tsconfig.base.json

```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
tsconfig still had an old reference to the file structure before the new lib structure. This caused some code editors to not pick up the tsconfig correctly and highlight wrong things in the angular-tree-component lib folder.
Removed old reference.
```
[ ] Yes
[x] No
```

refactor: adjust tsconfig

---

package-lock.json
package.json
projects/angular-tree-component/package.json

closes #862
```
[x] Bugfix
[ ] Feature
```
Closes #862
```
[ ] Yes
[x] No
```

fix: update lodash-es

---

projects/angular-tree-component/src/lib/models/tree-options.model.ts
projects/angular-tree-component/tslint.json

closes #889
- [x The commit message follows our guidelines: https://github.com/CirclonGroup/angular-tree-component/blob/master/CONTRIBUTING.md#commit-message-guidelines
```
[x] Bugfix
[ ] Feature
```
Closes #889 
No more logs
```
[ ] Yes
[x] No
```

fix: remove log calls

---

projects/angular-tree-component/src/lib/models/tree-options.model.ts

closes #891
```
[x] Bugfix
[ ] Feature
```
Closes #891
Undefined optional action mappings don't break the default mappings.
```
[ ] Yes
[x] No
```

fix: merge default and optional action mappings

---

README.md
projects/docs-app/src/app/examples/basic-usage/basic-usage.component.html
projects/docs-app/src/app/examples/columns-example/columns-example.component.html
projects/docs-app/src/app/examples/crud-example/crud-example.component.html
projects/docs-app/src/app/examples/load-more-example/load-more-example.component.html
projects/docs-app/src/app/fundamentals/actions/actions.component.html
projects/docs-app/src/app/fundamentals/api/api.component.html
projects/docs-app/src/app/fundamentals/state-binding/state-binding.component.html
projects/docs-app/src/app/fundamentals/templates/templates.component.html
projects/docs-app/src/app/guides/async-guide/async-guide.component.html
projects/docs-app/src/app/guides/auto-scroll-guide/auto-scroll-guide.component.html
projects/docs-app/src/app/guides/checkboxes-guide/checkboxes-guide.component.html
projects/docs-app/src/app/guides/drag-drop-guide/drag-drop-guide.component.html
projects/docs-app/src/app/guides/filter-guide/filter-guide.component.html
projects/docs-app/src/app/guides/large-tree-guide/large-tree-guide.component.html
projects/docs-app/src/app/guides/rtl-guide/rtl-guide.component.html

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Closes #
Added links to the source code for all demos in the documentation.
```
[ ] Yes
[x] No
```

docs: add github source code links
